### ISSUE TITLE
improve command line arg handling

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/henge#15]
Use urfave/cli lib for cmd line handling, rather than plain `flags` or `os`

**Comment by surajssd** [comment]
lib: https://github.com/urfave/cli

**Comment by kadel** [comment]
I would also consider cobra library - https://github.com/spf13/cobra that is used by Docker, OpenShift, Kubernets

**Comment by cdrage** [comment]
I agree with @kadel although urfave/cli has more stars, cobra is a lot more robust :100:

**Comment by pradeepto** [comment]
Let's go for robust. Btw, how many active contributors should be something we should consider.

**Comment by kadel** [comment]
this is also related to #4

**Comment by surajssd** [comment]
okay then lets go with cobra!

**Comment by surajssd** [comment]
Also now that we have interactive mode, also we need to put those things in command line args like `--image` or `--ports` something of that sort.

**Comment by surajssd** [comment]
@kadel one query, we are also planning to add flags to apply info that user can give from interactive mode like port number and image name, so what will be the flags named and how will we know what service to assign things to?

**Comment by kadel** [comment]
@surajssd that is a good question. I don't have answer right now :confused: 
It would be nice to have this, but I'm not sure if we can even do that
I think that as a first step we should at least warn user that something might be missing (see  #27). This could be enough for now.

**Comment by surajssd** [comment]
@kadel right now we can go with the improvement in cmdline and we will add those things once we get to a consensus!

**Comment by surajssd** [comment]
cmdline handling with cobra has been added https://github.com/redhat-developer/henge/pull/32

**Comment by kadel** [comment]
#32 is merged, I think we can close this now.
