### ISSUE TITLE
Interactive mode - Asking for port

### ISSUE THREAD

**Issue by kadel** [redhat-developer/henge#30]
In help for this question we should describe how we expect that user will specify port. Probably something like "80:8888"

Another thing is that we should allow user to provide multiple ports. For example by separating them with space like this "80:8888 443:8443"

**Comment by surajssd** [comment]
@kadel in help telling a user how to specify port number, where should this help be? In the interactive question itself?

**Comment by kadel** [comment]
I think that it should be in question itself, or at  least there should be an example of format in  we expect it.

**Comment by surajssd** [comment]
@kadel this is how the interface looks like: https://github.com/redhat-developer/henge/pull/39#issue-163873585 

What do you say?
