### ISSUE TITLE
provider should be verified before proceeding

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/henge#43]
Running this:

```bash
[vagrant@compose ~]$ henge xyz
file "docker-compose.yml" not found
```

This should return some output like, `unknown provider: xyz` or `unknown argument: xyz` and not look for a docker-compose.yml file.

**Comment by surajssd** [comment]
Even if right provider is given this error still persists

```
$ ll
total 40448
-rwxrwxr-x. 1 vagrant vagrant 41416456 Jul  7 11:10 henge

$ ./henge openshift
file "docker-compose.yml" not found
```

**Comment by containscafeine** [comment]
Right, I am proposing similar behavior as `argparse` in python, which throws an error if it does not recognize a positional/optional argument.
